---
env:
  - MOZ_HEADLESS=1
services:
  - mysql
sudo: true
addons:
  firefox: latest
dist: trusty
before_install:
  - "gem update --system"
  - "gem install bundler"
before_script:
  - mysql -e 'CREATE DATABASE best_before_test;'
language: ruby
script:
  - "bundle exec rubocop"
  - "bundle exec rspec"