---
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
  - "gem update --system"
  - "gem install bundler"
before_script:
  - "bundle exec rails db:create db:test:prepare"
language: ruby
script:
  - "bundle exec rspec"