---
env:
  - MOZ_HEADLESS=1
services:
  - mysql
addons:
  firefox: latest
  apt:
    sources:
      - mysql-5.7-trusty
dist: trusty
before_install:
  - "gem update --system"
  - "gem install bundler"
before_script:
  - "bundle exec rails db:create db:test:prepare"
language: ruby
script:
  - "bundle exec rubocop"
  - "bundle exec rspec"